language: node_js
node_js:
  - 14.4.0
cache: yarn

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - yarn gh-pages

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
